"""
    Autobahn App API

    Was passiert auf Deutschlands Bundesstraßen? API für aktuelle Verwaltungsdaten zu Baustellen, Staus und Ladestationen. Außerdem Zugang zu Verkehrsüberwachungskameras und vielen weiteren Datensätzen.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland import autobahn
from deutschland.autobahn.model.electric_charging_station import ElectricChargingStation
globals()['ElectricChargingStation'] = ElectricChargingStation
from deutschland.autobahn.model.electric_charging_stations import ElectricChargingStations


class TestElectricChargingStations(unittest.TestCase):
    """ElectricChargingStations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElectricChargingStations(self):
        """Test ElectricChargingStations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ElectricChargingStations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
