"""
    Autobahn App API

    Was passiert auf Deutschlands Bundesstraßen? API für aktuelle Verwaltungsdaten zu Baustellen, Staus und Ladestationen. Außerdem Zugang zu Verkehrsüberwachungskameras und vielen weiteren Datensätzen.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland import autobahn
from deutschland.autobahn.model.road_id import RoadId
globals()['RoadId'] = RoadId
from deutschland.autobahn.model.roads import Roads


class TestRoads(unittest.TestCase):
    """Roads unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoads(self):
        """Test Roads"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Roads()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
