"""
    Autobahn App API

    Was passiert auf Deutschlands Bundesstraßen? API für aktuelle Verwaltungsdaten zu Baustellen, Staus und Ladestationen. Außerdem Zugang zu Verkehrsüberwachungskameras und vielen weiteren Datensätzen.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland import autobahn
from deutschland.autobahn.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_charging_station(self):
        """Test case for get_charging_station

        Details zu einer Ladestation  # noqa: E501
        """
        pass

    def test_get_closure(self):
        """Test case for get_closure

        Details zu einer Sperrung  # noqa: E501
        """
        pass

    def test_get_parking_lorry(self):
        """Test case for get_parking_lorry

        Details eines Rastplatzes  # noqa: E501
        """
        pass

    def test_get_roadwork(self):
        """Test case for get_roadwork

        Details einer Baustelle  # noqa: E501
        """
        pass

    def test_get_warning(self):
        """Test case for get_warning

        Details zu einer Verkehrsmeldung  # noqa: E501
        """
        pass

    def test_get_webcam(self):
        """Test case for get_webcam

        Details einer Webcam  # noqa: E501
        """
        pass

    def test_list_autobahnen(self):
        """Test case for list_autobahnen

        Liste verfügbarer Autobahnen  # noqa: E501
        """
        pass

    def test_list_charging_stations(self):
        """Test case for list_charging_stations

        Liste aktueller Ladestationen  # noqa: E501
        """
        pass

    def test_list_closures(self):
        """Test case for list_closures

        Liste aktueller Sperrungen  # noqa: E501
        """
        pass

    def test_list_parking_lorries(self):
        """Test case for list_parking_lorries

        Liste verfügbarer Rastplätze  # noqa: E501
        """
        pass

    def test_list_roadworks(self):
        """Test case for list_roadworks

        Liste aktueller Baustellen  # noqa: E501
        """
        pass

    def test_list_warnings(self):
        """Test case for list_warnings

        Liste aktueller Verkehrsmeldungen  # noqa: E501
        """
        pass

    def test_list_webcams(self):
        """Test case for list_webcams

        Liste verfügbarer Webcams  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
