"""
    Autobahn App API

    Was passiert auf Deutschlands Bundesstraßen? API für aktuelle Verwaltungsdaten zu Baustellen, Staus und Ladestationen. Außerdem Zugang zu Verkehrsüberwachungskameras und vielen weiteren Datensätzen.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: kontakt@autobahn.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.autobahn.model.lorry_parking_feature_icon import (
    LorryParkingFeatureIcon,
)

from deutschland import autobahn


class TestLorryParkingFeatureIcon(unittest.TestCase):
    """LorryParkingFeatureIcon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLorryParkingFeatureIcon(self):
        """Test LorryParkingFeatureIcon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LorryParkingFeatureIcon()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
